# -*- coding: utf-8 -*-
"""Assignment 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXmS8r4nxAGOJp3b7K2twE3a-IID6Lra
"""



"""ASSIGNMENT 1"""

a = float(input ('enter first number :'))
b = float(input ('enter Second number:'))
add = a+b
sub = a-b
mul = a*b
div = a/b
print('\nAddition:', add )
print('Subtraction', sub)
print('Multiplication', mul)
print('Division', div)

a = input('enter your first name:')
b = input('enter your last name:')
c = a + " " + b
print('Hello,', c ,'! Welcome to python program :)')