# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXmS8r4nxAGOJp3b7K2twE3a-IID6Lra
"""



"""ASSIGNMENT 2
Task 1
"""

a = float(input ('enter  number :'))

if a % 2 == 0:
  print("It's a even number" )
else:
  print("It's a odd number")

"""Task 2

"""

sum = 0
for i in range(51):
  sum += i
print("sum of number 1 to 50 is :" ,sum)