# -*- coding: utf-8 -*-
"""Assignment 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXmS8r4nxAGOJp3b7K2twE3a-IID6Lra

Assignment 4, Task 1
"""

try:
 with open('sample.txt', 'r') as file1:
  reading_file = file1.readlines()
  for index, line in enumerate(reading_file, start=1):
        print(f"Line {index}: {line.strip()}")


except FileNotFoundError:
  print('Error: The file "sample.txt" does not exist')

"""Task 2"""

user_input = input("Enter some text to write to the file: ")

with open('output.txt', 'w') as file:
    file.write(user_input + '\n')

additional_input = input("Enter additional text to append to the file: ")
with open('output.txt', 'a') as file:

    file.write(additional_input + '\n')
print("\nFinal content of output.txt:")
with open('output.txt', 'r') as file:
    for index, line in enumerate(file, start=1):
        print(f"Line {index}: {line.strip()}")