# -*- coding: utf-8 -*-
"""Assignment 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXmS8r4nxAGOJp3b7K2twE3a-IID6Lra

Assignment 3, Task 1
"""

a = int(input('Enter a number'))
def factorial(a):
  sum = 1
  for i in range(1,a+1):
    sum *= i
  print('the factorial of the number is:', sum)
factorial(a)

"""Task 2"""

from math import *

a = int(input('Enter a number'))
angle_radians = radians(a)
print('sqrt of a no', sqrt(a))
print('Natural logarithm', log(a))
print('sine of the numbers', sin(angle_radians))